#声明微服务的web服务器端口号
server:
  port: 9001

#声明微服务的应用名称
spring:
  application:
    name: microservice-user
  #设置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.80.140:3306/jsd21132?charecterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

   #设置JPA正向工程
  jpa:
    #访问数据库产品
    database: mysql
    #生成建表语句，自动建表
    generate-ddl: true
    #显示sql语句
    show-sql: true
  #zipkin服务器的IP地址
  zipkin:
    base-url:http://192.168.80.1:9041
    sender:
      type: web
  #跟踪样本采样率是100%
  sleuth:
    sampler:
      probability: 1

#eureka客户端
eureka:
  client:
    #eureka客户端向eureka服务器注册
    register-with-eureka: true
    #向eureka服务器索要信息
    fetch-registry: true
    #注册服务的url
    service-url:
      defaultZone: http://192.168.80.1:8888/eureka

  #用户微服务的提供方与eureka服务器的约定
  instance:
    #每30秒发送一次心跳
    lease-renewal-interval-in-seconds: 30 #默认时间是30秒
    #租借到期的时间间隔是90秒,含义是90秒内eureka服务器没有接到一次心跳
    #表明注册的微服务失效,可以删除了
    lease-expiration-duration-in-seconds: 90 #默认时间是90秒
